### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by hasanneke** [hasanneke/givit#6]
- My Requests
- Favorites
- Phone, Email, Name, Surname, Profile Pic, Address

**Comment by HyperactiveDuck** [comment]
-Animations, animation controllers, stack positioning and responsive UI.

My Requests
Favorites
Phone, Email, Name, Surname, Profile Pic, Address


bunlar eklenecek

**Comment by hasanneke** [comment]
Drawer home'a taşınacak. Düzenleme butonu eklenecek.
